### PR TITLE
magic command is now running tests

### PR DESCRIPTION
**Pull request by superjan**
Looks better. I don't have included it into any CMakeLists file, hope anyone can do this bc I am not really a pro in understanding CMake. 

@felixangell Can you tell me which includes aren't needed anymore now in the ``main.c`` file?

### CODE REVIEW

**Comment by raoulvdberge** [comment]
Should be as simple as adding it to the sources:

<code>file(GLOB SOURCES ${CMAKE_SOURCE_DIR}/src/*.c ${CMAKE_SOURCE_DIR}/src/toml/*.c ${CMAKE_SOURCE_DIR}/src/actions/*.c ${CMAKE_SOURCE_DIR}/src/toml_test/*.c)</code>

**Comment by felixangell** [comment]
Cool, I'll merge it if you make it so that `arkade magic` will run the tests :wink:

**Comment by superjan** [comment]
@felixangell Ok should I then create an own action for it, so it passes better into the whole structure?

**Comment by felixangell** [comment]
@superjan Hmm, yeah why not :)

**Comment by superjan** [comment]
@felixangell Will do this later bc i am not at home lol

**Comment by felixangell** [comment]
lol no rush :)

**Comment by superjan** [comment]
@felixangell Think it will work now.

**Comment by raoulvdberge** [comment]
can you fix the merge conflicts? :)

**Comment by superjan** [comment]
@raoulvdberge Cannot see any conflicts here. Show me please :)

**Comment by felixangell** [comment]
It says you have conflicts that should be resolved. Have you rebased with the upstream?

```
git remote add upstream http://github.com/ark-lang/arkade
git fetch upstream
git merge upstream/master
```

It looks like you haven't because your repo says: `This branch is 4 commits ahead, 7 commits behind ark-lang:master`

**Comment by superjan** [comment]
``git merge upstream/master`` is giving me an error

```
$ git merge upstream/master
Auto-merging src/main.c
CONFLICT (content): Merge conflict in src/main.c
Auto-merging src/arguments.c
Auto-merging include/actions.h
CONFLICT (content): Merge conflict in include/actions.h
Automatic merge failed; fix conflicts and then commit the result.
```

**Comment by felixangell** [comment]
Cool :)

**Comment by superjan** [comment]
There is one problem, there are now things like https://github.com/ark-lang/arkade/blob/master/src/main.c#L10

**Comment by felixangell** [comment]
oh lol, those are merge conflicts. I'll sort those out

**Comment by superjan** [comment]
@felixangell ok thx

**Comment by felixangell** [comment]
Fixed stuff, though the realistic test is run relatively from the current directory, so I might have to do some tweaking.

**Pull request merged**
